FROM python:3.13-slim

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY test_main.py .

CMD ["python", "main.py"]